### ISSUE TITLE
Discussion: Which Elixir/Erlang versions should we target

### ISSUE THREAD

**Issue by Raphexion** [witchtails/planning#3]
I suggest that we follow the official [Compatibility and deprecations](https://hexdocs.pm/elixir/main/compatibility-and-deprecations.html) document:

In my mind we should only support the last three (non-development releases):

|Elixir version  | Support |
|- |- |
|~~1.17~~ |	~~Development~~ |
|1.16 |	Bug fixes and security patches |
|1.15 |	Security patches only |
|1.14 |	Security patches only |

(Clearly the exact version will change in the future, but to give an example of the last three)

For example in our github actions, we should use this as our basis for our matrix:

```
steps:
  - uses: erlef/setup-beam@v1
    with:
      otp-version: ${{matrix.otp}}
      elixir-version: ${{matrix.elixir}}
```
